//! The generated capsule config: the serialization boundary between the
//! offline fit pipeline and the runtime model.
//!
//! The JSON file is generated by the `fit_capsules` bin, checked in next to
//! the assets, and hand-tunable. Loading parses it into validated runtime
//! types ([`LoadedConfig`]); nothing downstream re-checks invariants. The
//! pairs section carries a fingerprint of the capsules it was classified
//! against, so a refit without reclassification fails to load instead of
//! silently running with stale margins.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use srs_model::nalgebra::Point3;

use crate::geometry::Capsule;
use crate::pairs::PairSpec;

/// One capsule as stored on disk: plain arrays, link-local or world frame
/// depending on the section it appears in.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapsuleSpec {
    pub a: [f64; 3],
    pub b: [f64; 3],
    pub radius: f64,
}

/// A named body (a URDF link, or a fixed structure) and its capsules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BodyCapsules {
    pub name: String,
    pub capsules: Vec<CapsuleSpec>,
}

/// The on-disk config layout.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollisionConfig {
    /// Basename of the URDF the capsules were fitted from, for provenance.
    pub source_urdf: String,
    /// World-frame capsules of bodies that never move (torso, mount links).
    pub fixed: Vec<BodyCapsules>,
    /// Link-frame capsules of the moving links, keyed by URDF link name.
    /// A link may carry several capsules (the wrist also carries the
    /// worst-case-open finger capsules).
    pub links: Vec<BodyCapsules>,
    /// The checked pairs with per-pair margins, written by `classify_pairs`.
    /// Empty until classification has run.
    #[serde(default)]
    pub pairs: Vec<PairSpec>,
    /// Fingerprint of the capsule sections the pairs were classified
    /// against, written by `classify_pairs`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pairs_fingerprint: Option<u64>,
}

/// Validated, runtime-ready form of the config.
#[derive(Debug, Clone)]
pub struct LoadedConfig {
    pub source_urdf: String,
    pub fixed: Vec<(String, Vec<Capsule>)>,
    pub links: HashMap<String, Vec<Capsule>>,
    pub pairs: Vec<PairSpec>,
}

impl CapsuleSpec {
    fn parse(&self, context: &str) -> Result<Capsule, String> {
        let nums = self.a.iter().chain(&self.b).chain([&self.radius]);
        if nums.into_iter().any(|x| !x.is_finite()) {
            return Err(format!("{context}: capsule has non-finite values"));
        }
        if self.radius <= 0.0 {
            return Err(format!("{context}: capsule radius {} must be positive", self.radius));
        }
        Ok(Capsule {
            a: Point3::new(self.a[0], self.a[1], self.a[2]),
            b: Point3::new(self.b[0], self.b[1], self.b[2]),
            radius: self.radius,
        })
    }

    pub fn from_capsule(c: &Capsule) -> Self {
        Self { a: [c.a.x, c.a.y, c.a.z], b: [c.b.x, c.b.y, c.b.z], radius: c.radius }
    }
}

impl CollisionConfig {
    pub fn from_json(json: &str) -> Result<Self, String> {
        serde_json::from_str(json).map_err(|e| format!("parse capsule config: {e}"))
    }

    pub fn from_file(path: &str) -> Result<Self, String> {
        let json = std::fs::read_to_string(path).map_err(|e| format!("read capsule config '{path}': {e}"))?;
        Self::from_json(&json)
    }

    pub fn to_json_pretty(&self) -> String {
        serde_json::to_string_pretty(self).expect("config serialization cannot fail")
    }

    /// Validate every capsule and index the link sections.
    pub fn parse(self) -> Result<LoadedConfig, String> {
        let parse_body = |b: &BodyCapsules| -> Result<(String, Vec<Capsule>), String> {
            if b.capsules.is_empty() {
                return Err(format!("body '{}' has no capsules", b.name));
            }
            let capsules = b
                .capsules
                .iter()
                .enumerate()
                .map(|(i, s)| s.parse(&format!("{}[{i}]", b.name)))
                .collect::<Result<Vec<_>, _>>()?;
            Ok((b.name.clone(), capsules))
        };

        let fixed = self.fixed.iter().map(parse_body).collect::<Result<Vec<_>, _>>()?;
        let mut links = HashMap::new();
        for body in &self.links {
            let (name, capsules) = parse_body(body)?;
            if links.insert(name, capsules).is_some() {
                return Err(format!("duplicate link '{}' in capsule config", body.name));
            }
        }
        for p in &self.pairs {
            if p.a == p.b {
                return Err(format!("pair '{}' against itself", p.a));
            }
            if !p.margin.is_finite() {
                return Err(format!("pair {}/{} has non-finite margin", p.a, p.b));
            }
        }
        if !self.pairs.is_empty() {
            match self.pairs_fingerprint {
                Some(f) if f != self.capsules_fingerprint() => {
                    return Err("capsules changed since pairs were classified; rerun classify_pairs".into());
                }
                _ => {}
            }
        }
        Ok(LoadedConfig { source_urdf: self.source_urdf, fixed, links, pairs: self.pairs })
    }

    /// FNV-1a over the capsule geometry (micrometer grid), the quantity the
    /// pair classification depends on.
    pub fn capsules_fingerprint(&self) -> u64 {
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        let mut eat = |x: f64| {
            for b in ((x * 1e6).round() as i64).to_le_bytes() {
                h ^= b as u64;
                h = h.wrapping_mul(0x0000_0100_0000_01B3);
            }
        };
        for body in self.fixed.iter().chain(&self.links) {
            for c in &body.capsules {
                c.a.iter().chain(&c.b).chain([&c.radius]).for_each(|v| eat(*v));
            }
        }
        h
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec(radius: f64) -> CapsuleSpec {
        CapsuleSpec { a: [0.0, 0.0, 0.0], b: [0.0, 0.0, 0.1], radius }
    }

    fn config(radius: f64) -> CollisionConfig {
        CollisionConfig {
            source_urdf: "x.urdf".into(),
            fixed: vec![BodyCapsules { name: "body".into(), capsules: vec![spec(radius)] }],
            links: vec![BodyCapsules { name: "link1".into(), capsules: vec![spec(radius)] }],
            pairs: vec![PairSpec::new("body", "link1")],
            pairs_fingerprint: None,
        }
    }

    #[test]
    fn json_roundtrip_preserves_values() {
        let c = config(0.05);
        let back = CollisionConfig::from_json(&c.to_json_pretty()).expect("roundtrip");
        let loaded = back.parse().expect("valid");
        assert_eq!(loaded.links["link1"][0].radius, 0.05);
        assert_eq!(loaded.fixed[0].0, "body");
        assert_eq!(loaded.pairs, vec![PairSpec::new("body", "link1")]);
    }

    #[test]
    fn pairs_section_is_optional_in_json() {
        // Configs written before classification (or hand-stripped) load with
        // no pairs rather than failing.
        let json = r#"{"source_urdf":"x.urdf","fixed":[],"links":[
            {"name":"link1","capsules":[{"a":[0,0,0],"b":[0,0,0.1],"radius":0.05}]}]}"#;
        let loaded = CollisionConfig::from_json(json).expect("parse").parse().expect("valid");
        assert!(loaded.pairs.is_empty());
    }

    #[test]
    fn rejects_bad_radius_nonfinite_and_duplicates() {
        assert!(config(0.0).parse().is_err());
        assert!(config(-0.1).parse().is_err());
        assert!(config(f64::NAN).parse().is_err());

        let mut dup = config(0.05);
        dup.links.push(dup.links[0].clone());
        assert!(dup.parse().is_err());

        let mut empty = config(0.05);
        empty.links[0].capsules.clear();
        assert!(empty.parse().is_err());
    }

    #[test]
    fn stale_pairs_fingerprint_is_rejected() {
        let mut c = config(0.05);
        c.pairs_fingerprint = Some(c.capsules_fingerprint());
        assert!(c.clone().parse().is_ok());
        c.links[0].capsules[0].radius = 0.06; // refit without reclassify
        assert!(c.clone().parse().is_err());
        c.pairs.clear(); // no pairs, no staleness to enforce
        assert!(c.parse().is_ok());
    }

    #[test]
    fn self_and_nonfinite_pairs_are_rejected() {
        let mut c = config(0.05);
        c.pairs = vec![PairSpec::new("body", "body")];
        assert!(c.clone().parse().is_err());
        c.pairs = vec![PairSpec { a: "body".into(), b: "link1".into(), margin: f64::NAN }];
        assert!(c.parse().is_err());
    }

    #[test]
    fn from_capsule_roundtrips_through_parse() {
        let c = Capsule { a: Point3::new(0.1, 0.2, 0.3), b: Point3::new(0.4, 0.5, 0.6), radius: 0.07 };
        let parsed = CapsuleSpec::from_capsule(&c).parse("t").expect("valid");
        assert_eq!(parsed, c);
    }
}
