"""The types of workspace_core_py, the extension module built from src/lib.rs."""

from collections.abc import Iterable
from typing import ClassVar, Final, final

type _Vector3 = tuple[float, float, float]
"""A point or a direction, ``(x, y, z)``."""

type _Bounds = tuple[float, float, float, float]
"""The bounds of a rectangle, ``(x_min, x_max, y_min, y_max)``."""

REACH_TOLERANCE: Final[float]
GRASP_ANGLE_TOLERANCE: Final[float]
ABOVE_SURFACE: Final[float]
GRASP_DIRECTIONS: Final[tuple[GraspDirection, ...]]

@final
class GraspDirection:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @property
    def name(self) -> str: ...
    @property
    def approach(self) -> _Vector3: ...

def angle_between(a: Iterable[float], b: Iterable[float]) -> float: ...

@final
class SurfaceHeight:
    @staticmethod
    def from_wire(metres: float) -> SurfaceHeight: ...
    @property
    def metres(self) -> float: ...
    def grid_targets(self) -> list[_Vector3]: ...
    def __hash__(self) -> int: ...

@final
class Positions:
    @staticmethod
    def from_wire(values: Iterable[float]) -> Positions: ...
    @property
    def points(self) -> list[_Vector3]: ...
    def __len__(self) -> int: ...

@final
class Reach:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @staticmethod
    def reached_by(arm: str) -> Reach: ...
    @staticmethod
    def short(by: float) -> Reach: ...
    @property
    def reached(self) -> bool: ...
    @property
    def arm(self) -> str: ...
    @property
    def short_by(self) -> float: ...

@final
class SurfaceReach:
    @staticmethod
    def from_grid_order(
        height: SurfaceHeight, reaches: Iterable[Reach]
    ) -> SurfaceReach: ...
    @property
    def height(self) -> SurfaceHeight: ...
    @property
    def reaches(self) -> list[Reach]: ...

@final
class ReachMemo:
    def __init__(self) -> None: ...
    def get(self, height: SurfaceHeight) -> SurfaceReach | None: ...
    def insert(self, surface: SurfaceReach) -> SurfaceReach: ...
    def __len__(self) -> int: ...

@final
class SurfaceAnswer:
    @property
    def workable(self) -> bool: ...
    @property
    def area(self) -> float: ...
    @property
    def rectangle(self) -> _Bounds | None: ...
    @property
    def reach(self) -> _Bounds | None: ...
    @property
    def view(self) -> _Bounds | None: ...
    @property
    def message(self) -> str: ...

@final
class PointAnswer:
    @property
    def position(self) -> _Vector3: ...
    @property
    def reach(self) -> Reach: ...
    @property
    def view(self) -> str: ...
    @property
    def in_view(self) -> bool: ...
    @property
    def workable(self) -> bool: ...
    @property
    def message(self) -> str: ...

@final
class PositionsAnswer:
    @property
    def points(self) -> list[PointAnswer]: ...
    @property
    def all_workable(self) -> bool: ...
    @property
    def message(self) -> str: ...

def describe_without_perception_camera(surface: SurfaceReach) -> SurfaceAnswer: ...
def check_without_perception_camera(
    positions: Positions, reaches: Iterable[Reach]
) -> PositionsAnswer: ...
